name: integration

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  integration:
    runs-on: ubuntu-latest
    env:
        DOCKER_BUILDKIT: 1
        COMPOSE_DOCKER_CLI_BUILD: 1
    steps:
      # Monorepo tests
      - uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build the services
        working-directory: ./ops
        run: ./scripts/build-ci.sh

      - name: Bring the stack up and wait for the sequencer to be ready
        working-directory: ./ops
        run: docker-compose up -d && ./scripts/wait-for-sequencer.sh

      - name: Run the integration tests
        working-directory: ./integration-tests
        run: |
            yarn build:contracts
            yarn build:contracts:ovm
            yarn test:integration

      # optimism-tutorial tests
      - name: Install optimism-tutorial dependencies
        working-directory: ./examples/optimism-tutorial
        run: yarn

      - name: Compile optimism-tutorial contracts
        working-directory: ./examples/optimism-tutorial
        run: yarn hardhat compile && yarn hardhat --network optimism compile

      - name: Test optimism-tutorial contracts
        working-directory: ./examples/optimism-tutorial
        run: yarn hardhat test && yarn hardhat test --network optimism 

      - name: Deploy optimism-tutorial contracts
        working-directory: ./examples/optimism-tutorial
        run: yarn hardhat deploy && yarn hardhat deploy --network optimism
